version: '2'
services:

  airflow:
    image: ghcr.io/ezynook/apache-airflow/airflow:2.8.0-pgsql
    container_name: airflow
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./dags/:/root/airflow/dags